version: '3.1'

services:

  site:
    build: .
    depends_on:
      - database
    volumes:
      - uploads:/var/www/html/public/uploads
      - fileadmin:/var/www/html/public/fileadmin
      - ./public/.htaccess:/var/www/html/public/.htaccess
      - ./public/typo3conf/ext/news:/var/www/html/public/typo3conf/ext/news
    ports:
      - "8080:80"

  database:
    image: mariadb:latest
    environment:
      MYSQL_USER: typo3
      MYSQL_PASSWORD: typo3
      MYSQL_DATABASE: typo3
      MYSQL_ROOT_PASSWORD: typo3
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - database:/var/lib/mysql

volumes:
  uploads:
    driver: local
  fileadmin:
    driver: local
  database:
    driver: local
