version: '3.1'

services:

  site:
    build: ./docker/site
    restart: unless-stopped
    networks:
      - default
      - public
    volumes:
      - .:/var/www/html
    labels:
      - traefik.port=80
      - traefik.enable=true
      - traefik.backend=frontend
      - traefik.frontend.rule=Host:mysite.test
      - traefik.frontend.passHostHeader=true
      - traefik.docker.network=public

  database:
    image: mariadb:latest
    restart: unless-stopped
    # env_file: .env
    networks:
      - default
    environment:
      MYSQL_USER: typo3
      MYSQL_PASSWORD: typo3
      MYSQL_DATABASE: typo3
      MYSQL_ROOT_PASSWORD: typo3
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - database:/var/lib/mysql
    labels:
      - traefik.enable=false

volumes:
  database:
    driver: local

networks:
  public:
    external:
      name: public
