version: "3"

services:
  templates:
    image: "php:7.3-apache"
    restart: unless-stopped
    volumes:
      - "./assets:/var/www/html"
    labels:
      - traefik.port=80
      - traefik.enable=true
      - traefik.backend=frontend
      - traefik.frontend.rule=Host:template.project.mydomain.com
      - traefik.frontend.passHostHeader=true
      - traefik.docker.network=public

  database:
    image: "mysql:5.7"
    restart: unless-stopped
    ports:
      - "4407:3306"
    environment:
      MYSQL_USER: "typo3"
      MYSQL_PASSWORD: "typo3"
      MYSQL_DATABASE: "typo3"
      MYSQL_ROOT_PASSWORD: "typo3"
    command:
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    volumes:
      - "database:/var/lib/mysql"
    labels:
      - "traefik.enable=false"
      
  typo3:
    image: "myrepo/typo3:9.5"
    restart: unless-stopped
    environment:
      - "TYPO3_CONTEXT=${CONTEXT}"
    volumes:
      - "$PWD/fileadmin:/var/www/html/fileadmin"
      - "$PWD/typo3conf:/var/www/html/typo3conf"
      - "$PWD/uploads:/var/www/html/uploads"
    labels:
      - traefik.port=80
      - traefik.enable=true
      - traefik.backend=frontend
      - traefik.frontend.rule=Host:project.mydomain.com
      - traefik.frontend.passHostHeader=true
      - traefik.docker.network=public

volumes:
  database:
    driver: local
