version: '3.1'

services:

  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/traefik:/etc/traefik
      # TODO check win
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=false

